export const labels: Record<string, string> = {
  running: '运行中',
  started: '已启动',
  resumed: '已恢复',
  approved: '已批准',
  skipped: '已跳过',
  saved: '已保存',
  completed: '已完成',
  committed: '已定稿',
  paused: '已暂停',
  needs_author_decision: '待决策',
  stopped: '已停止',
  failed: '失败',
  pending: '待处理',
  ready: '就绪',
  blocked: '阻断',
  warning: '有警告',
  error: '异常',
  draft: '草稿',
  revision: '修订稿',
  rejected: '已拒绝',
  active: '进行中',
  dormant: '休眠',
  resolved: '已解决',
  done: '已完成',
  open: '待处理',
  confirmed: '已确认',
  verified: '已验证',
  closed: '已关闭',
  PASS: '通过',
  WARN: '警告',
  BLOCK: '阻断',
  NOT_REVIEWED: '待审校',
  knowledge_leak: '知识泄漏',
  continuity: '连续性',
  narrative: '叙事',
  character: '人物',
  semantic_knowledge_leak: '语义 · 泄漏',
  semantic_character: '语义 · 人物',
  semantic_narrative: '语义 · 叙事',
  semantic_pacing: '语义 · 节奏',
  Character: '人物',
  Faction: '势力',
  Location: '地点',
  Artifact: '器物',
  Item: '物品',
  Power: '力量',
  Skill: '技能',
  Organization: '组织',
  Realm: '境界',
  Concept: '概念',
  Creature: '生灵',
  Resource: '资源',
  Bloodline: '血脉',
  Race: '种族',
  mainline: '主线',
  mystery: '谜团',
  relationship: '关系',
  conflict: '冲突',
  worldbuilding: '世界',
  Clue: '线索',
  Payoff: '兑现',
  Reveal: '揭示',
  Mystery: '谜团',
  EmotionDebt: '情感债',
  plan: '规划',
  planning: '规划',
  run: '启动',
  chapter: '章节',
  review: '审校',
  revise: '修订',
  commit: '定稿',
  decision: '决策',
  hard: '近期确定',
  medium: '中期安排',
  soft: '远期方向',
  model: 'AI 生成',
  external: '导入',
  web_edit: '手动编辑',
  web_restore: '版本恢复',
  steering_point: '等待引导',
  plan_approval: '计划待审核',
  public: '公开',
  secret: '剧情秘密',
}
export const label = (value?: string | null) => (value ? labels[value] || value : '—')
export const statusTone = (value?: string): 'pass' | 'block' | 'warn' | 'canon' | 'draft' | 'muted' =>
  ['BLOCK', 'blocked', 'failed', 'error'].includes(value || '')
    ? 'block'
    : ['WARN', 'warning', 'paused', 'needs_author_decision'].includes(value || '')
      ? 'warn'
      : ['PASS', 'ready', 'running'].includes(value || '')
        ? 'pass'
        : ['completed', 'committed', 'resolved'].includes(value || '')
          ? 'canon'
          : ['draft', 'revision'].includes(value || '')
            ? 'draft'
            : 'muted'
