"""官方 MCP Python SDK v2 适配器。
安装:pip install 'mcp>=2,<3'
运行:mcp run server.py --transport stdio
     mcp run server.py --transport streamable-http
"""
from __future__ import annotations
from typing import Any
from mcp.server import MCPServer
from .runtime import call_tool

mcp=MCPServer('Narrative-KG Novel Writing')

def expose(name):
    def deco(fn): fn.__name__=name; return mcp.tool(name=name)(fn)
    return deco

@expose('story_get_state')
def story_get_state(chapter:int,recent_window:int=10)->dict[str,Any]: return call_tool('story_get_state',locals())
@expose('narrative_thread_get')
def narrative_thread_get(thread_key:str)->dict[str,Any]: return call_tool('narrative_thread_get',locals())
@expose('narrative_thread_search')
def narrative_thread_search(query:str='',status:str|None=None,thread_type:str|None=None,limit:int=20)->list[dict[str,Any]]: return call_tool('narrative_thread_search',locals())
@expose('mystery_create')
def mystery_create(mystery_key:str,name:str,thread_key:str,introduced_chapter:int,target_min_chapter:int|None=None,target_max_chapter:int|None=None,notes:str='')->dict[str,Any]: return call_tool('mystery_create',locals())
@expose('clue_add')
def clue_add(thread_key:str,chapter:int,content:str,visibility:str='reader',strength:float=.2,holder:str|None=None,callback_key:str|None=None)->dict[str,Any]: return call_tool('clue_add',locals())
@expose('foreshadowing_list_open')
def foreshadowing_list_open(before_chapter:int,min_age:int=100,limit:int=30)->list[dict[str,Any]]: return call_tool('foreshadowing_list_open',locals())
@expose('belief_get')
def belief_get(fact_key:str,chapter:int)->dict[str,Any]: return call_tool('belief_get',locals())
@expose('belief_update')
def belief_update(fact_key:str,holder:str,chapter:int,stance:str,value:Any=None,confidence:float=1.0,source:str='author_declared')->dict[str,Any]: return call_tool('belief_update',locals())
@expose('emotion_debt_create')
def emotion_debt_create(debt_key:str,thread_key:str,name:str,emotion_type:str,intensity:float,created_chapter:int,target_holder:str|None=None,notes:str='')->dict[str,Any]: return call_tool('emotion_debt_create',locals())
@expose('emotion_debt_resolve')
def emotion_debt_resolve(debt_key:str,chapter:int,content:str,resolution:str='full',consequence:str='')->dict[str,Any]: return call_tool('emotion_debt_resolve',locals())
@expose('narrative_pattern_search')
def narrative_pattern_search(pattern:str='',min_span:int=0,need:list[str]|None=None,limit:int=10)->dict[str,Any]: return call_tool('narrative_pattern_search',locals())
@expose('chapter_plan_check')
def chapter_plan_check(chapter:int,plan:dict[str,Any],pov_holder:str='reader')->dict[str,Any]: return call_tool('chapter_plan_check',locals())
@expose('continuity_check')
def continuity_check(chapter:int,proposed_facts:list[dict[str,Any]]|None=None,character_states:list[dict[str,Any]]|None=None,entities:list[dict[str,Any]]|None=None,entity_attributes:list[dict[str,Any]]|None=None,entity_relations:list[dict[str,Any]]|None=None)->dict[str,Any]: return call_tool('continuity_check',locals())
@expose('story_pressure_check')
def story_pressure_check(chapter:int,mystery_age:int=200,foreshadow_age:int=300,debt_age:int=200,recent_window:int=30)->dict[str,Any]: return call_tool('story_pressure_check',locals())
# chapter_commit v0.8 起不再对外暴露:正典提交统一走 chapter_finalize 审校门。

# 实体图 / 世界模型 v0.6
@expose('entity_get')
def entity_get(entity_key:str,chapter:int,holder:str='reader')->dict[str,Any]: return call_tool('entity_get',locals())
@expose('entity_author_get')
def entity_author_get(entity_key:str,chapter:int)->dict[str,Any]: return call_tool('entity_author_get',locals())
@expose('entity_search')
def entity_search(query:str='',entity_type:str|None=None,status:str|None='active',chapter:int=0,holder:str='reader',limit:int=20)->list[dict[str,Any]]: return call_tool('entity_search',locals())
@expose('entity_neighbors')
def entity_neighbors(entity_key:str,chapter:int,holder:str='reader',relation_types:list[str]|None=None,direction:str='both',depth:int=1,limit:int=100)->dict[str,Any]: return call_tool('entity_neighbors',locals())
@expose('entity_path_find')
def entity_path_find(source_entity_key:str,target_entity_key:str,chapter:int,holder:str='reader',relation_types:list[str]|None=None,max_depth:int=4)->dict[str,Any]: return call_tool('entity_path_find',locals())
@expose('entity_context_get')
def entity_context_get(entity_keys:list[str],chapter:int,holder:str='reader',depth:int=1,limit:int=100)->dict[str,Any]: return call_tool('entity_context_get',locals())
@expose('entity_graph_stats')
def entity_graph_stats()->dict[str,Any]: return call_tool('entity_graph_stats',{})
@expose('entity_upsert')
def entity_upsert(entity_key:str,entity_type:str,name:str,chapter:int|None=None,status:str='active',description:str='',properties:dict[str,Any]|None=None,source:str='author_declared')->dict[str,Any]: return call_tool('entity_upsert',locals())
@expose('entity_alias_add')
def entity_alias_add(entity_key:str,alias:str,alias_type:str='alias',secrecy:str='public',reveal_after:int|None=None,fact_key:str|None=None,source:str='author_declared')->dict[str,Any]: return call_tool('entity_alias_add',locals())
@expose('entity_attribute_set')
def entity_attribute_set(entity_key:str,attr_key:str,value:Any,chapter:int=0,end_chapter:int|None=None,secrecy:str='public',reveal_after:int|None=None,fact_key:str|None=None,source:str='author_declared',confidence:float=1.0,close_previous:bool=True,cause_event_id:int|None=None)->dict[str,Any]: return call_tool('entity_attribute_set',locals())
@expose('entity_relation_upsert')
def entity_relation_upsert(source_entity_key:str,relation_type:str,target_entity_key:str,start_chapter:int=0,end_chapter:int|None=None,status:str='active',secrecy:str='public',reveal_after:int|None=None,fact_key:str|None=None,properties:dict[str,Any]|None=None,source:str='author_declared',cause_event_id:int|None=None)->dict[str,Any]: return call_tool('entity_relation_upsert',locals())
@expose('entity_relation_end')
def entity_relation_end(source_entity_key:str,relation_type:str,target_entity_key:str,chapter:int)->dict[str,Any]: return call_tool('entity_relation_end',locals())
@expose('narrative_entity_link')
def narrative_entity_link(narrative_type:str,narrative_key:str,entity_key:str,role:str='involves',chapter:int=0,properties:dict[str,Any]|None=None,source:str='author_declared')->dict[str,Any]: return call_tool('narrative_entity_link',locals())
@expose('narrative_entity_links_get')
def narrative_entity_links_get(entity_key:str|None=None,narrative_type:str|None=None,narrative_key:str|None=None,limit:int=100)->list[dict[str,Any]]: return call_tool('narrative_entity_links_get',locals())
@expose('entity_graph_check')
def entity_graph_check(chapter:int,entities:list[dict[str,Any]]|None=None,attributes:list[dict[str,Any]]|None=None,relations:list[dict[str,Any]]|None=None)->dict[str,Any]: return call_tool('entity_graph_check',locals())
@expose('entity_graph_import')
def entity_graph_import(graph:dict[str,Any],namespace:str='story',include_types:list[str]|None=None,dry_run:bool=True)->dict[str,Any]: return call_tool('entity_graph_import',locals())

# 检索与上下文编译器 v0.7
@expose('entity_retrieve_relevant')
def entity_retrieve_relevant(chapter:int,role:str='writer',holder:str|None=None,limit:int=30,max_depth:int=2)->dict[str,Any]: return call_tool('entity_retrieve_relevant',locals())
@expose('narrative_retrieve_relevant')
def narrative_retrieve_relevant(chapter:int,role:str='writer',holder:str|None=None,limit:int=20)->dict[str,Any]: return call_tool('narrative_retrieve_relevant',locals())
@expose('context_compile')
def context_compile(chapter:int,role:str='writer',holder:str|None=None,max_tokens:int|None=None,recent_window:int|None=None,excerpt_chars:int|None=None,include_reference:bool|None=None,persist:bool=False)->dict[str,Any]: return call_tool('context_compile',locals())
@expose('context_preview')
def context_preview(chapter:int,role:str='writer',holder:str|None=None,max_tokens:int|None=None)->dict[str,Any]: return call_tool('context_preview',locals())
@expose('context_snapshot_get')
def context_snapshot_get(snapshot_id:str|None=None,chapter:int|None=None,role:str|None=None)->dict[str,Any]: return call_tool('context_snapshot_get',locals())
@expose('context_explain')
def context_explain(snapshot_id:str,item_key:str|None=None)->dict[str,Any]: return call_tool('context_explain',locals())

# 规划运行时 v0.2
@expose('blueprint_get')
def blueprint_get()->dict[str,Any]: return call_tool('blueprint_get',{})
@expose('blueprint_update')
def blueprint_update(patch:dict[str,Any],replace:bool=False,expected_version:int|None=None)->dict[str,Any]: return call_tool('blueprint_update',locals())
@expose('story_architect_get')
def story_architect_get()->dict[str,Any]: return call_tool('story_architect_get',{})
@expose('story_architect_apply')
def story_architect_apply(architecture:dict[str,Any],dry_run:bool=False)->dict[str,Any]: return call_tool('story_architect_apply',locals())
@expose('arc_plan_create')
def arc_plan_create(arc:dict[str,Any])->dict[str,Any]: return call_tool('arc_plan_create',locals())
@expose('arc_plan_get')
def arc_plan_get(arc_key:str)->dict[str,Any]: return call_tool('arc_plan_get',locals())
@expose('arc_progress_get')
def arc_progress_get(arc_key:str,chapter:int|None=None)->dict[str,Any]: return call_tool('arc_progress_get',locals())
@expose('milestone_create')
def milestone_create(milestone:dict[str,Any])->dict[str,Any]: return call_tool('milestone_create',locals())
@expose('milestone_list')
def milestone_list(arc_key:str|None=None,status:str|None=None,before_chapter:int|None=None,limit:int=100)->list[dict[str,Any]]: return call_tool('milestone_list',locals())
@expose('thread_schedule_update')
def thread_schedule_update(schedule:dict[str,Any])->dict[str,Any]: return call_tool('thread_schedule_update',locals())
@expose('thread_schedule_get')
def thread_schedule_get(schedule_key:str|None=None,thread_key:str|None=None,chapter:int|None=None,status:str|None=None,limit:int=100)->list[dict[str,Any]]: return call_tool('thread_schedule_get',locals())
@expose('planning_rebuild_window')
def planning_rebuild_window(anchor_chapter:int,hard_horizon:int=5,medium_horizon:int=20,soft_horizon:int=50,proposals:list[dict[str,Any]]|None=None,preserve_existing:bool=True)->dict[str,Any]: return call_tool('planning_rebuild_window',locals())
@expose('planning_get_window')
def planning_get_window(anchor_chapter:int,horizon:int=50)->dict[str,Any]: return call_tool('planning_get_window',locals())
@expose('chapter_plan_save')
def chapter_plan_save(chapter:int,plan:dict[str,Any],pov_holder:str='reader',arc_key:str|None=None,status:str='draft',allow_blocked:bool=True)->dict[str,Any]: return call_tool('chapter_plan_save',locals())
@expose('chapter_plan_get')
def chapter_plan_get(chapter:int)->dict[str,Any]: return call_tool('chapter_plan_get',locals())
@expose('planning_pressure_check')
def planning_pressure_check(chapter:int,hard_lookahead:int=5)->dict[str,Any]: return call_tool('planning_pressure_check',locals())

# 作者规划器 / 小说运行控制器 v0.5
@expose('planner_context_get')
def planner_context_get(chapter:int,recent_window:int=10)->dict[str,Any]: return call_tool('planner_context_get',locals())
@expose('chapter_plan_generate')
def chapter_plan_generate(chapter:int,model:str|None=None,save:bool=True,allow_blocked:bool=False)->dict[str,Any]: return call_tool('chapter_plan_generate',locals())
@expose('novel_run_start')
def novel_run_start(start_chapter:int|None=None,target_chapter:int|None=None,target_arc_key:str|None=None,max_chapters:int|None=None,max_revision_rounds:int=3,require_semantic:bool=True,allow_warnings:bool=True,auto_extract:bool=False,auto_plan:bool=True,stop_on_pressure:bool=True,pressure_risk_limit:int=4,report_every:int=10,hard_horizon:int=5,medium_horizon:int=20,soft_horizon:int=50,planner_model:str|None=None,writer_model:str|None=None,reviewer_model:str|None=None,revision_model:str|None=None)->dict[str,Any]: return call_tool('novel_run_start',locals())
@expose('novel_run_step')
def novel_run_step(run_id:str)->dict[str,Any]: return call_tool('novel_run_step',locals())
@expose('novel_run_continue')
def novel_run_continue(run_id:str,max_steps:int=5)->dict[str,Any]: return call_tool('novel_run_continue',locals())
@expose('novel_run_status')
def novel_run_status(run_id:str)->dict[str,Any]: return call_tool('novel_run_status',locals())
@expose('novel_run_pause')
def novel_run_pause(run_id:str,reason:str='')->dict[str,Any]: return call_tool('novel_run_pause',locals())
@expose('novel_run_resume')
def novel_run_resume(run_id:str)->dict[str,Any]: return call_tool('novel_run_resume',locals())
@expose('novel_run_report')
def novel_run_report(run_id:str,persist:bool=False)->dict[str,Any]: return call_tool('novel_run_report',locals())
@expose('novel_run_decision_list')
def novel_run_decision_list(run_id:str,status:str|None='open')->list[dict[str,Any]]: return call_tool('novel_run_decision_list',locals())
@expose('novel_run_decision_submit')
def novel_run_decision_submit(run_id:str,decision_id:str,resolution:dict[str,Any])->dict[str,Any]: return call_tool('novel_run_decision_submit',locals())

# 写作 / 审校运行时 v0.4
@expose('writer_context_get')
def writer_context_get(chapter:int,recent_window:int=8,excerpt_chars:int=500)->dict[str,Any]: return call_tool('writer_context_get',locals())
@expose('chapter_draft_generate')
def chapter_draft_generate(chapter:int,title:str|None=None,model:str|None=None,declared_updates:dict[str,Any]|None=None,summary:str='')->dict[str,Any]: return call_tool('chapter_draft_generate',locals())
@expose('chapter_draft_save')
def chapter_draft_save(chapter:int,title:str,body:str,arc:str='',pov:str='',summary:str='',declared_updates:dict[str,Any]|None=None,source:str='external',model:str='',parent_version:int|None=None)->dict[str,Any]: return call_tool('chapter_draft_save',locals())
@expose('chapter_draft_get')
def chapter_draft_get(chapter:int,version:int|None=None)->dict[str,Any]: return call_tool('chapter_draft_get',locals())
@expose('chapter_review_all')
def chapter_review_all(chapter:int,version:int|None=None)->dict[str,Any]: return call_tool('chapter_review_all',locals())
@expose('chapter_review_get')
def chapter_review_get(chapter:int,version:int|None=None)->dict[str,Any]: return call_tool('chapter_review_get',locals())
@expose('chapter_revision_context_get')
def chapter_revision_context_get(chapter:int,version:int|None=None)->dict[str,Any]: return call_tool('chapter_revision_context_get',locals())
@expose('writing_workflow_status')
def writing_workflow_status(chapter:int)->dict[str,Any]: return call_tool('writing_workflow_status',locals())
@expose('chapter_finalize')
def chapter_finalize(chapter:int,version:int|None=None,allow_warnings:bool=True,auto_extract:bool=False,override_block:bool=False,override_reason:str='',require_semantic:bool=False)->dict[str,Any]: return call_tool('chapter_finalize',locals())

@expose('chapter_semantic_review')
def chapter_semantic_review(chapter:int,version:int|None=None,model:str|None=None)->dict[str,Any]: return call_tool('chapter_semantic_review',locals())
@expose('chapter_review_full')
def chapter_review_full(chapter:int,version:int|None=None,semantic:bool=True,model:str|None=None)->dict[str,Any]: return call_tool('chapter_review_full',locals())
@expose('chapter_auto_revise')
def chapter_auto_revise(chapter:int,version:int|None=None,model:str|None=None,include_warnings:bool=True)->dict[str,Any]: return call_tool('chapter_auto_revise',locals())
@expose('chapter_auto_revision_loop')
def chapter_auto_revision_loop(chapter:int,version:int|None=None,max_rounds:int=3,require_semantic:bool=True,reviewer_model:str|None=None,revision_model:str|None=None,finalize:bool=False,allow_warnings:bool=True,auto_extract:bool=False)->dict[str,Any]: return call_tool('chapter_auto_revision_loop',locals())

# 抽取候选晋升闭环 v0.8 (A0)
@expose('candidate_list')
def candidate_list(chapter:int|None=None,node_type:str|None=None,status:str='candidate',limit:int=100)->list[dict[str,Any]]: return call_tool('candidate_list',locals())
@expose('candidate_promote')
def candidate_promote(candidate_id:int,target:dict[str,Any]|None=None)->dict[str,Any]: return call_tool('candidate_promote',locals())
@expose('candidate_reject')
def candidate_reject(candidate_id:int,reason:str='')->dict[str,Any]: return call_tool('candidate_reject',locals())

# 世界模型 V2:身份档案 / 一等事件 / 断言
@expose('identity_profile_set')
def identity_profile_set(profile:dict[str,Any])->dict[str,Any]: return call_tool('identity_profile_set',locals())
@expose('event_create')
def event_create(name:str,chapter:int,event_key:str|None=None,event_type:str='event',thread_key:str|None=None,location_key:str|None=None,cause_event_id:int|None=None,cause_event_key:str|None=None,outcome:str='',consequence:str='',status:str='verified',participants:list[dict[str,Any]]|None=None,metadata:dict[str,Any]|None=None)->dict[str,Any]: return call_tool('event_create',locals())
@expose('event_get')
def event_get(event_key:str|None=None,event_id:int|None=None)->dict[str,Any]: return call_tool('event_get',locals())
@expose('event_timeline')
def event_timeline(entity_key:str|None=None,from_chapter:int|None=None,to_chapter:int|None=None,limit:int=100)->list[dict[str,Any]]: return call_tool('event_timeline',locals())
@expose('assertion_create')
def assertion_create(subject_key:str,predicate:str,object_value:Any=None,chapter:int=0,subject_type:str='entity',source_span:str|None=None,extractor:str='author_declared',confidence:float=1.0,evidence:str|None=None,event_id:int|None=None)->dict[str,Any]: return call_tool('assertion_create',locals())
@expose('assertion_list')
def assertion_list(subject_key:str|None=None,subject_type:str|None=None,predicate:str|None=None,truth_status:str|None=None,limit:int=100)->list[dict[str,Any]]: return call_tool('assertion_list',locals())
@expose('assertion_resolve')
def assertion_resolve(assertion_id:int,truth_status:str,superseded_by:int|None=None)->dict[str,Any]: return call_tool('assertion_resolve',locals())

# 双时序披露 + 专业子图(Phase A 第二批)
@expose('fact_disclosure_set')
def fact_disclosure_set(fact_key:str,holder:str,known_from_chapter:int,channel:str='',source:str='author_declared')->dict[str,Any]: return call_tool('fact_disclosure_set',locals())
@expose('fact_disclosures_get')
def fact_disclosures_get(fact_key:str|None=None)->list[dict[str,Any]]: return call_tool('fact_disclosures_get',locals())
@expose('power_context_get')
def power_context_get(entity_key:str,chapter:int)->dict[str,Any]: return call_tool('power_context_get',locals())
@expose('artifact_history_get')
def artifact_history_get(entity_key:str)->dict[str,Any]: return call_tool('artifact_history_get',locals())
@expose('geography_tree_get')
def geography_tree_get(root_entity_key:str,chapter:int,holder:str='reader',relation_types:list[str]|None=None,max_depth:int=4,limit:int=100)->dict[str,Any]: return call_tool('geography_tree_get',locals())
