from __future__ import annotations
from typing import Any

EMPTY_OBJ={"type":"object","additionalProperties":False}
ANY_OBJ={"type":"object"}

TOOLS: list[dict[str,Any]] = [
 {"name":"story_get_state","title":"Get Story State","description":"Get the canonical writing context for a chapter: arc, goals, active threads, open mysteries, emotion debts, reader/character beliefs, forbidden world truths, due foreshadowing, and recent events.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"recent_window":{"type":"integer","minimum":1,"maximum":50,"default":10}},"required":["chapter"],"additionalProperties":False}},
 {"name":"narrative_thread_get","title":"Get Narrative Thread","description":"Return the full lifecycle of one Story Graph narrative thread.","inputSchema":{"type":"object","properties":{"thread_key":{"type":"string","minLength":1}},"required":["thread_key"],"additionalProperties":False}},
 {"name":"narrative_thread_search","title":"Search Narrative Threads","description":"Search Story Graph threads by text, status, or type.","inputSchema":{"type":"object","properties":{"query":{"type":"string","default":""},"status":{"type":"string"},"thread_type":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":100,"default":20}},"additionalProperties":False}},
 {"name":"mystery_create","title":"Create Mystery","description":"Create or register a reader-facing long-form mystery and its intended payoff window.","inputSchema":{"type":"object","properties":{"mystery_key":{"type":"string","minLength":1},"name":{"type":"string","minLength":1},"thread_key":{"type":"string","minLength":1},"introduced_chapter":{"type":"integer","minimum":0},"target_min_chapter":{"type":"integer","minimum":0},"target_max_chapter":{"type":"integer","minimum":0},"notes":{"type":"string","default":""}},"required":["mystery_key","name","thread_key","introduced_chapter"],"additionalProperties":False}},
 {"name":"clue_add","title":"Add Clue","description":"Add a clue to a narrative thread with controlled visibility and information strength. A clue is not automatically a verified foreshadowing until a later callback exists.","inputSchema":{"type":"object","properties":{"thread_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0},"content":{"type":"string","minLength":1},"visibility":{"type":"string","enum":["reader","character","private_author"],"default":"reader"},"strength":{"type":"number","minimum":0,"maximum":1,"default":0.2},"holder":{"type":"string"},"callback_key":{"type":"string"}},"required":["thread_key","chapter","content"],"additionalProperties":False}},
 {"name":"foreshadowing_list_open","title":"List Open Foreshadowing","description":"List old unresolved clues/foreshadowing that need reactivation or payoff.","inputSchema":{"type":"object","properties":{"before_chapter":{"type":"integer","minimum":0},"min_age":{"type":"integer","minimum":0,"default":100},"limit":{"type":"integer","minimum":1,"maximum":100,"default":30}},"required":["before_chapter"],"additionalProperties":False}},
 {"name":"belief_get","title":"Get Belief State","description":"Return world truth plus reader and character beliefs for one fact at a chapter, without collapsing them into one value.","inputSchema":{"type":"object","properties":{"fact_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0}},"required":["fact_key","chapter"],"additionalProperties":False}},
 {"name":"belief_update","title":"Update Belief State","description":"Record a change in what the reader or a character believes/suspects/knows about a fact.","inputSchema":{"type":"object","properties":{"fact_key":{"type":"string","minLength":1},"holder":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0},"stance":{"type":"string","enum":["unknown","suspects","believes","confirmed","disbelieves"]},"value":{},"confidence":{"type":"number","minimum":0,"maximum":1,"default":1},"source":{"type":"string","default":"author_declared"}},"required":["fact_key","holder","chapter","stance"],"additionalProperties":False}},
 {"name":"emotion_debt_create","title":"Create Emotion Debt","description":"Create a long-lived emotional debt such as humiliation, promise, sacrifice, loss, misunderstanding, or revenge obligation.","inputSchema":{"type":"object","properties":{"debt_key":{"type":"string","minLength":1},"thread_key":{"type":"string","minLength":1},"name":{"type":"string","minLength":1},"emotion_type":{"type":"string","minLength":1},"intensity":{"type":"number","minimum":0,"maximum":1},"created_chapter":{"type":"integer","minimum":0},"target_holder":{"type":"string"},"notes":{"type":"string","default":""}},"required":["debt_key","thread_key","name","emotion_type","intensity","created_chapter"],"additionalProperties":False}},
 {"name":"emotion_debt_resolve","title":"Resolve Emotion Debt","description":"Resolve or partially resolve an emotion debt with a payoff event.","inputSchema":{"type":"object","properties":{"debt_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0},"content":{"type":"string","minLength":1},"resolution":{"type":"string","enum":["partial","full"],"default":"full"},"consequence":{"type":"string","default":""}},"required":["debt_key","chapter","content"],"additionalProperties":False}},
 {"name":"narrative_pattern_search","title":"Search Reference Narrative Patterns","description":"Search the read-only Reference Graph for structural examples. Returns abstract structure and evidence metadata, never source prose.","inputSchema":{"type":"object","properties":{"pattern":{"type":"string","default":""},"min_span":{"type":"integer","minimum":0,"default":0},"need":{"type":"array","items":{"type":"string"},"default":[]},"limit":{"type":"integer","minimum":1,"maximum":50,"default":10}},"additionalProperties":False}},
 {"name":"chapter_plan_check","title":"Check Chapter Plan","description":"Validate a proposed chapter plan against secret world truths, current beliefs, thread timing, and declared reveal rules before prose is written.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"pov_holder":{"type":"string","default":"reader"},"plan":{"type":"object"}},"required":["chapter","plan"],"additionalProperties":False}},
 {"name":"continuity_check","title":"Check Continuity","description":"Check proposed world facts, character states, Entity Graph changes, and timeline assertions against canonical Story Graph state.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"proposed_facts":{"type":"array","items":{"type":"object"},"default":[]},"character_states":{"type":"array","items":{"type":"object"},"default":[]},"entities":{"type":"array","items":{"type":"object"},"default":[]},"entity_attributes":{"type":"array","items":{"type":"object"},"default":[]},"entity_relations":{"type":"array","items":{"type":"object"},"default":[]}},"required":["chapter"],"additionalProperties":False}},
 {"name":"story_pressure_check","title":"Check Story Pressure","description":"Measure unresolved mystery load, stale foreshadowing, overdue emotion debt, recent opening/closing rates, and recommend pressure relief.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"mystery_age":{"type":"integer","minimum":1,"default":200},"foreshadow_age":{"type":"integer","minimum":1,"default":300},"debt_age":{"type":"integer","minimum":1,"default":200},"recent_window":{"type":"integer","minimum":5,"maximum":100,"default":30}},"required":["chapter"],"additionalProperties":False}},
 # chapter_commit v0.8 起从公开工具面移除:正典提交唯一入口是 chapter_finalize。


 # 实体图 / 世界模型 v0.6
 {"name":"entity_get","title":"Get Entity (Safe View)","description":"Get one Story Entity at a chapter using Reader/POV visibility. Secret aliases, attributes, and relations are filtered unless legally revealed or known by the holder.","inputSchema":{"type":"object","properties":{"entity_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0},"holder":{"type":"string","default":"reader"}},"required":["entity_key","chapter"],"additionalProperties":False}},
 {"name":"entity_author_get","title":"Get Entity (Author View)","description":"Author-layer full Entity Graph read including hidden aliases, attributes, and relations. Never expose this tool to prose-only Writer agents.","inputSchema":{"type":"object","properties":{"entity_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0}},"required":["entity_key","chapter"],"additionalProperties":False}},
 {"name":"entity_search","title":"Search Entities","description":"Search Story Entity Graph by stable key, safe name/visible alias, type, and status. Secret aliases are not a search side-channel.","inputSchema":{"type":"object","properties":{"query":{"type":"string","default":""},"entity_type":{"type":"string"},"status":{"type":"string","default":"active"},"chapter":{"type":"integer","minimum":0,"default":0},"holder":{"type":"string","default":"reader"},"limit":{"type":"integer","minimum":1,"maximum":200,"default":20}},"additionalProperties":False}},
 {"name":"entity_neighbors","title":"Get Entity Neighborhood","description":"Traverse visible Entity Graph relations around one entity for continuity and context retrieval.","inputSchema":{"type":"object","properties":{"entity_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0},"holder":{"type":"string","default":"reader"},"relation_types":{"type":"array","items":{"type":"string"}},"direction":{"type":"string","enum":["both","out","in"],"default":"both"},"depth":{"type":"integer","minimum":1,"maximum":4,"default":1},"limit":{"type":"integer","minimum":1,"maximum":500,"default":100}},"required":["entity_key","chapter"],"additionalProperties":False}},
 {"name":"entity_path_find","title":"Find Entity Path","description":"Find a short visible relationship path between two Story entities without traversing hidden relations the current holder should not know.","inputSchema":{"type":"object","properties":{"source_entity_key":{"type":"string","minLength":1},"target_entity_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0},"holder":{"type":"string","default":"reader"},"relation_types":{"type":"array","items":{"type":"string"}},"max_depth":{"type":"integer","minimum":1,"maximum":6,"default":4}},"required":["source_entity_key","target_entity_key","chapter"],"additionalProperties":False}},
 {"name":"entity_context_get","title":"Get Safe Entity Context","description":"Build a compact visibility-filtered Entity Graph context for selected characters, factions, places, items, skills, realms, artifacts, or events.","inputSchema":{"type":"object","properties":{"entity_keys":{"type":"array","items":{"type":"string"},"minItems":1,"maxItems":50},"chapter":{"type":"integer","minimum":0},"holder":{"type":"string","default":"reader"},"depth":{"type":"integer","minimum":0,"maximum":4,"default":1},"limit":{"type":"integer","minimum":1,"maximum":500,"default":100}},"required":["entity_keys","chapter"],"additionalProperties":False}},
 {"name":"entity_graph_stats","title":"Get Entity Graph Stats","description":"Get Entity Graph counts and type/relation distributions for author diagnostics.","inputSchema":{"type":"object","properties":{},"additionalProperties":False}},
 {"name":"entity_upsert","title":"Upsert Entity","description":"Create or update a canonical Story entity. Keep entity name/properties non-secret; store hidden identity/details as secret aliases/attributes/relations linked to World Facts.","inputSchema":{"type":"object","properties":{"entity_key":{"type":"string","minLength":1},"entity_type":{"type":"string","minLength":1},"name":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0},"status":{"type":"string","default":"active"},"description":{"type":"string","default":""},"properties":{"type":"object"},"source":{"type":"string","default":"author_declared"}},"required":["entity_key","entity_type","name"],"additionalProperties":False}},
 {"name":"entity_alias_add","title":"Add Entity Alias","description":"Add an alias/title/identity label with optional secrecy, reveal window, and World Fact binding.","inputSchema":{"type":"object","properties":{"entity_key":{"type":"string","minLength":1},"alias":{"type":"string","minLength":1},"alias_type":{"type":"string","default":"alias"},"secrecy":{"type":"string","enum":["public","secret","author_only"],"default":"public"},"reveal_after":{"type":"integer","minimum":0},"fact_key":{"type":"string"},"source":{"type":"string","default":"author_declared"}},"required":["entity_key","alias"],"additionalProperties":False}},
 {"name":"entity_attribute_set","title":"Set Entity Attribute","description":"Set a temporal entity attribute such as realm, injury, identity state, age, capability, or status with optional secrecy and World Fact binding.","inputSchema":{"type":"object","properties":{"entity_key":{"type":"string","minLength":1},"attr_key":{"type":"string","minLength":1},"value":{},"chapter":{"type":"integer","minimum":0,"default":0},"end_chapter":{"type":"integer","minimum":0},"secrecy":{"type":"string","enum":["public","secret","author_only"],"default":"public"},"reveal_after":{"type":"integer","minimum":0},"fact_key":{"type":"string"},"source":{"type":"string","default":"author_declared"},"confidence":{"type":"number","minimum":0,"maximum":1,"default":1},"close_previous":{"type":"boolean","default":True},"cause_event_id":{"type":"integer","minimum":1,"description":"optional event this state change is caused by; enables state-change traceability"}},"required":["entity_key","attr_key","value"],"additionalProperties":False}},
 {"name":"entity_relation_upsert","title":"Upsert Entity Relation","description":"Create/update a temporal relation such as PARENT_OF, MEMBER_OF, LOCATED_IN, OWNS, USES, ENEMY_OF, ALLY_OF, MASTER_OF, or custom relation.","inputSchema":{"type":"object","properties":{"source_entity_key":{"type":"string","minLength":1},"relation_type":{"type":"string","minLength":1},"target_entity_key":{"type":"string","minLength":1},"start_chapter":{"type":"integer","minimum":0,"default":0},"end_chapter":{"type":"integer","minimum":0},"status":{"type":"string","default":"active"},"secrecy":{"type":"string","enum":["public","secret","author_only"],"default":"public"},"reveal_after":{"type":"integer","minimum":0},"fact_key":{"type":"string"},"properties":{"type":"object"},"source":{"type":"string","default":"author_declared"},"cause_event_id":{"type":"integer","minimum":1,"description":"optional event this relation change is caused by"}},"required":["source_entity_key","relation_type","target_entity_key"],"additionalProperties":False}},
 {"name":"entity_relation_end","title":"End Entity Relation","description":"End an active temporal Entity Graph relation at a chapter without deleting historical truth.","inputSchema":{"type":"object","properties":{"source_entity_key":{"type":"string","minLength":1},"relation_type":{"type":"string","minLength":1},"target_entity_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0}},"required":["source_entity_key","relation_type","target_entity_key","chapter"],"additionalProperties":False}},
 {"name":"narrative_entity_link","title":"Link Narrative Object to Entity","description":"Bind NarrativeThread/Mystery/EmotionDebt/WorldFact/Event/Stage to an Entity so narrative planning can traverse into the World Model.","inputSchema":{"type":"object","properties":{"narrative_type":{"type":"string","minLength":1},"narrative_key":{"type":"string","minLength":1},"entity_key":{"type":"string","minLength":1},"role":{"type":"string","default":"involves"},"chapter":{"type":"integer","minimum":0,"default":0},"properties":{"type":"object"},"source":{"type":"string","default":"author_declared"}},"required":["narrative_type","narrative_key","entity_key"],"additionalProperties":False}},
 {"name":"narrative_entity_links_get","title":"Get Narrative Entity Links","description":"Query cross-layer links between Entity Graph and Narrative Graph.","inputSchema":{"type":"object","properties":{"entity_key":{"type":"string"},"narrative_type":{"type":"string"},"narrative_key":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":500,"default":100}},"additionalProperties":False}},
 {"name":"entity_graph_check","title":"Check Entity Graph Changes","description":"Validate proposed entities, temporal attributes, and relations before applying them to canonical World Model state.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"entities":{"type":"array","items":{"type":"object"},"default":[]},"attributes":{"type":"array","items":{"type":"object"},"default":[]},"relations":{"type":"array","items":{"type":"object"},"default":[]}},"required":["chapter"],"additionalProperties":False}},
 {"name":"entity_graph_import","title":"Import Entity Graph","description":"Import generic node/edge entity data into the Story Entity Graph. Dry-run by default. Never import the read-only reference novel graph into a new Story Graph.","inputSchema":{"type":"object","properties":{"graph":{"type":"object"},"namespace":{"type":"string","default":"story"},"include_types":{"type":"array","items":{"type":"string"}},"dry_run":{"type":"boolean","default":True}},"required":["graph"],"additionalProperties":False}},

 # 检索与上下文编译器 v0.7
 {"name":"entity_retrieve_relevant","title":"Retrieve Relevant Entities","description":"Rank chapter-relevant Story Entity Graph nodes using deterministic ChapterPlan, POV, location, active-thread, recency, and unresolved-obligation signals. Applies role-specific visibility and chapter time slicing.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":1},"role":{"type":"string","enum":["writer","planner","reviewer"],"default":"writer"},"holder":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":100,"default":30},"max_depth":{"type":"integer","minimum":1,"maximum":2,"default":2}},"required":["chapter"],"additionalProperties":False}},
 {"name":"narrative_retrieve_relevant","title":"Retrieve Relevant Narrative State","description":"Rank chapter-relevant NarrativeThread, Mystery, EmotionDebt and recent stage state using ChapterPlan, schedule, age, recency and unresolved-obligation signals, with Writer visibility filtering.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":1},"role":{"type":"string","enum":["writer","planner","reviewer"],"default":"writer"},"holder":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":100,"default":20}},"required":["chapter"],"additionalProperties":False}},
 {"name":"context_compile","title":"Compile Chapter Context","description":"Compile a role-isolated, chapter-sliced, relevance-ranked and token-budgeted context package for Planner, Writer or Reviewer. Writer context never contains hidden World Truth values. Optionally persists an immutable audit snapshot.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":1},"role":{"type":"string","enum":["writer","planner","reviewer"],"default":"writer"},"holder":{"type":"string"},"max_tokens":{"type":"integer","minimum":1000,"maximum":64000},"recent_window":{"type":"integer","minimum":1,"maximum":50},"excerpt_chars":{"type":"integer","minimum":0,"maximum":2000},"include_reference":{"type":"boolean"},"persist":{"type":"boolean","default":False}},"required":["chapter"],"additionalProperties":False}},
 {"name":"context_preview","title":"Preview Chapter Context","description":"Preview retrieval counts, top entities/threads and estimated token usage without persisting a context snapshot or returning full context payload.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":1},"role":{"type":"string","enum":["writer","planner","reviewer"],"default":"writer"},"holder":{"type":"string"},"max_tokens":{"type":"integer","minimum":1000,"maximum":64000}},"required":["chapter"],"additionalProperties":False}},
 {"name":"context_snapshot_get","title":"Get Context Snapshot (Author Audit)","description":"Get an immutable previously compiled context snapshot for audit/debugging. Author-only: Planner/Reviewer snapshots may contain hidden World Truth and must not be granted to prose-only Writer apps.","inputSchema":{"type":"object","properties":{"snapshot_id":{"type":"string"},"chapter":{"type":"integer","minimum":1},"role":{"type":"string","enum":["writer","planner","reviewer"]}},"additionalProperties":False}},
 {"name":"context_explain","title":"Explain Context Retrieval (Author Audit)","description":"Explain why an entity, narrative thread, or Reference pattern was included in a persisted context snapshot, including deterministic relevance reasons and score. Author/debug use.","inputSchema":{"type":"object","properties":{"snapshot_id":{"type":"string","minLength":1},"item_key":{"type":"string"}},"required":["snapshot_id"],"additionalProperties":False}},

 # 规划运行时 v0.2
 {"name":"blueprint_get","title":"Get Novel Blueprint","description":"Get the canonical high-level Novel Blueprint and its optimistic-lock version.","inputSchema":{"type":"object","properties":{},"additionalProperties":False}},
 {"name":"blueprint_update","title":"Update Novel Blueprint","description":"Patch or replace the canonical Novel Blueprint. Use expected_version to prevent concurrent planning overwrites.","inputSchema":{"type":"object","properties":{"patch":{"type":"object"},"replace":{"type":"boolean","default":False},"expected_version":{"type":"integer","minimum":1}},"required":["patch"],"additionalProperties":False}},
 {"name":"story_architect_get","title":"Get Story Architecture","description":"Get the compiled high-level architecture: Blueprint, arc plans, milestones, thread schedule, and canonical Story Graph counts.","inputSchema":{"type":"object","properties":{},"additionalProperties":False}},
 {"name":"story_architect_apply","title":"Apply Story Architecture","description":"Compile an author-designed architecture into canonical Story Graph and Planning state. Supports dry-run validation before mutation.","inputSchema":{"type":"object","properties":{"architecture":{"type":"object"},"dry_run":{"type":"boolean","default":False}},"required":["architecture"],"additionalProperties":False}},
 {"name":"novel_architecture_generate","title":"Generate Architecture From Idea","description":"Expand a one-sentence story idea into a complete cross-reference-valid architecture draft (blueprint, world truths, entity graph, threads/mysteries/debts, arcs/milestones/schedule) via a four-stage architect model. Generation is NOT application: review then call story_architect_apply.","inputSchema":{"type":"object","properties":{"idea":{"type":"string","minLength":1},"options":{"type":"object"}},"required":["idea"],"additionalProperties":False}},
 {"name":"arc_plan_create","title":"Create Arc Plan","description":"Create or update one arc plan with goals, conflict, reveal constraints, inherited threads, and exit conditions.","inputSchema":{"type":"object","properties":{"arc":{"type":"object"}},"required":["arc"],"additionalProperties":False}},
 {"name":"arc_plan_get","title":"Get Arc Plan","description":"Get one canonical arc plan.","inputSchema":{"type":"object","properties":{"arc_key":{"type":"string","minLength":1}},"required":["arc_key"],"additionalProperties":False}},
 {"name":"arc_progress_get","title":"Get Arc Progress","description":"Measure committed progress through an arc and return its milestones.","inputSchema":{"type":"object","properties":{"arc_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0}},"required":["arc_key"],"additionalProperties":False}},
 {"name":"milestone_create","title":"Create Planning Milestone","description":"Create or update a cross-chapter planning milestone with a target chapter window and success conditions.","inputSchema":{"type":"object","properties":{"milestone":{"type":"object"}},"required":["milestone"],"additionalProperties":False}},
 {"name":"milestone_list","title":"List Planning Milestones","description":"List arc milestones by arc, status, or deadline.","inputSchema":{"type":"object","properties":{"arc_key":{"type":"string"},"status":{"type":"string"},"before_chapter":{"type":"integer","minimum":0},"limit":{"type":"integer","minimum":1,"maximum":200,"default":100}},"additionalProperties":False}},
 {"name":"thread_schedule_update","title":"Update Thread Schedule","description":"Schedule a narrative thread stage into a chapter window without forcing exact prose or scene details.","inputSchema":{"type":"object","properties":{"schedule":{"type":"object"}},"required":["schedule"],"additionalProperties":False}},
 {"name":"thread_schedule_get","title":"Get Thread Schedule","description":"Query planned narrative-thread stages by schedule key, thread, chapter, or status.","inputSchema":{"type":"object","properties":{"schedule_key":{"type":"string"},"thread_key":{"type":"string"},"chapter":{"type":"integer","minimum":0},"status":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":200,"default":100}},"additionalProperties":False}},
 {"name":"planning_rebuild_window","title":"Rebuild Rolling Planning Window","description":"Build or retier a rolling Hard/Medium/Soft planning window. Optional proposals fill chapter goals while preserving existing plans by default.","inputSchema":{"type":"object","properties":{"anchor_chapter":{"type":"integer","minimum":0},"hard_horizon":{"type":"integer","minimum":1,"maximum":50,"default":5},"medium_horizon":{"type":"integer","minimum":1,"maximum":100,"default":20},"soft_horizon":{"type":"integer","minimum":1,"maximum":200,"default":50},"proposals":{"type":"array","items":{"type":"object"},"default":[]},"preserve_existing":{"type":"boolean","default":True}},"required":["anchor_chapter"],"additionalProperties":False}},
 {"name":"planning_get_window","title":"Get Rolling Planning Window","description":"Get chapter-level Hard/Medium/Soft rolling-plan items from an anchor chapter.","inputSchema":{"type":"object","properties":{"anchor_chapter":{"type":"integer","minimum":0},"horizon":{"type":"integer","minimum":1,"maximum":200,"default":50}},"required":["anchor_chapter"],"additionalProperties":False}},
 {"name":"chapter_plan_save","title":"Save Chapter Plan","description":"Save a structured ChapterPlan, run knowledge/reveal/arc/thread validators, and persist its validation status before prose is drafted.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"plan":{"type":"object"},"pov_holder":{"type":"string","default":"reader"},"arc_key":{"type":"string"},"status":{"type":"string","default":"draft"},"allow_blocked":{"type":"boolean","default":True}},"required":["chapter","plan"],"additionalProperties":False}},
 {"name":"chapter_plan_get","title":"Get Saved Chapter Plan","description":"Get the saved structured ChapterPlan and its last validation result.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0}},"required":["chapter"],"additionalProperties":False}},
 {"name":"planning_pressure_check","title":"Check Planning Pressure","description":"Combine story-pressure diagnostics with rolling-window completeness, overdue milestones, and overdue thread schedules.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"hard_lookahead":{"type":"integer","minimum":1,"maximum":20,"default":5}},"required":["chapter"],"additionalProperties":False}},
 # 作者规划器 / 小说运行控制器 v0.5
 {"name":"planner_context_get","title":"Get Author Planner Context","description":"Build author-layer planning context for one chapter. Unlike Writer context, this intentionally includes World Truth and must never be used directly as prose context.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":1},"recent_window":{"type":"integer","minimum":1,"maximum":50,"default":10}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_plan_generate","title":"Generate Chapter Plan","description":"Use the configured author-layer Planner model to generate and optionally save a structured ChapterPlan. Future World Truth may guide planning but remains subject to reveal validators.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":1},"model":{"type":"string"},"save":{"type":"boolean","default":True},"allow_blocked":{"type":"boolean","default":False}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_directive_set","title":"Set Chapter Directive","description":"Director steering: set the author's mandatory directive for one chapter. Injected into planner context; consumed after that chapter's plan is generated. Empty directive clears it.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":1},"directive":{"type":"string"},"source":{"type":"string","default":"author"}},"required":["chapter","directive"],"additionalProperties":False}},
{"name":"chapter_direction_propose","title":"Propose Chapter Directions","description":"Director co-creation: ask the model for N candidate directions for the next chapter based on current story state (threads, due obligations, dormant threads, aging debts). Proposals only; the author picks/edits before setting a directive.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":1},"count":{"type":"integer","minimum":1,"maximum":5,"default":3},"focus":{"type":"string","default":""}},"required":["chapter"],"additionalProperties":False}},
{"name":"novel_run_start","title":"Start Novel Run","description":"Start a persisted bounded Novel Run Controller loop. Configures automatic planning, writing, review/revision, commit, pressure stops, targets, and periodic reports.","inputSchema":{"type":"object","properties":{"start_chapter":{"type":"integer","minimum":1},"target_chapter":{"type":"integer","minimum":1},"target_arc_key":{"type":"string"},"max_chapters":{"type":"integer","minimum":1},"max_revision_rounds":{"type":"integer","minimum":0,"maximum":8,"default":3},"require_semantic":{"type":"boolean","default":True},"allow_warnings":{"type":"boolean","default":True},"auto_extract":{"type":"boolean","default":False},"auto_plan":{"type":"boolean","default":True},"stop_on_pressure":{"type":"boolean","default":True},"pressure_risk_limit":{"type":"integer","minimum":1,"maximum":100,"default":4},"report_every":{"type":"integer","minimum":1,"maximum":1000,"default":10},"hard_horizon":{"type":"integer","minimum":1,"maximum":50,"default":5},"medium_horizon":{"type":"integer","minimum":1,"maximum":100,"default":20},"soft_horizon":{"type":"integer","minimum":1,"maximum":200,"default":50},"planner_model":{"type":"string"},"writer_model":{"type":"string"},"reviewer_model":{"type":"string"},"revision_model":{"type":"string"}},"additionalProperties":False}},
 {"name":"novel_run_step","title":"Advance Novel Run One Chapter","description":"Execute at most one chapter transaction for a persisted Novel Run: ensure plan, draft, review/revise, finalize, record events, then advance or stop.","inputSchema":{"type":"object","properties":{"run_id":{"type":"string","minLength":1}},"required":["run_id"],"additionalProperties":False}},
 {"name":"novel_run_continue","title":"Continue Novel Run","description":"Advance a Novel Run for a bounded number of chapter steps. Stops early on target completion, pressure gates, review blocks, missing model configuration, pause, or author decision.","inputSchema":{"type":"object","properties":{"run_id":{"type":"string","minLength":1},"max_steps":{"type":"integer","minimum":1,"maximum":50,"default":5}},"required":["run_id"],"additionalProperties":False}},
 {"name":"novel_run_status","title":"Get Novel Run Status","description":"Inspect persisted run state, current/last chapter, stop reason, open author decisions, and recent controller events.","inputSchema":{"type":"object","properties":{"run_id":{"type":"string","minLength":1}},"required":["run_id"],"additionalProperties":False}},
 {"name":"novel_run_pause","title":"Pause Novel Run","description":"Pause an active Novel Run without losing chapter/run state.","inputSchema":{"type":"object","properties":{"run_id":{"type":"string","minLength":1},"reason":{"type":"string","default":""}},"required":["run_id"],"additionalProperties":False}},
 {"name":"novel_run_resume","title":"Resume Novel Run","description":"Resume a paused/decision-resolved Novel Run. Open author decisions must be resolved first.","inputSchema":{"type":"object","properties":{"run_id":{"type":"string","minLength":1}},"required":["run_id"],"additionalProperties":False}},
 {"name":"novel_run_report","title":"Generate Novel Run Report","description":"Generate a deterministic stage report for a Novel Run with committed chapters, controller events, current story/planning pressure, open decisions, and stop reason.","inputSchema":{"type":"object","properties":{"run_id":{"type":"string","minLength":1},"persist":{"type":"boolean","default":False}},"required":["run_id"],"additionalProperties":False}},
 {"name":"novel_run_decision_list","title":"List Novel Run Decisions","description":"List persisted human decision points for a Novel Run.","inputSchema":{"type":"object","properties":{"run_id":{"type":"string","minLength":1},"status":{"type":"string","default":"open"}},"required":["run_id"],"additionalProperties":False}},
 {"name":"novel_run_decision_submit","title":"Resolve Novel Run Decision","description":"Resolve a persisted author decision and optionally patch safe run configuration before resuming, pausing, or aborting the run.","inputSchema":{"type":"object","properties":{"run_id":{"type":"string","minLength":1},"decision_id":{"type":"string","minLength":1},"resolution":{"type":"object"}},"required":["run_id","decision_id","resolution"],"additionalProperties":False}},
 # 写作 / 审校运行时 v0.4
 {"name":"writer_context_get","title":"Get Safe Writer Context","description":"Build the prose-safe context for one chapter. Hidden World Truth values are intentionally withheld; only Reader/POV knowledge, approved plan, active threads, character state, and recent committed prose context are returned.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"recent_window":{"type":"integer","minimum":1,"maximum":30,"default":8},"excerpt_chars":{"type":"integer","minimum":0,"maximum":2000,"default":500}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_draft_generate","title":"Generate Chapter Draft","description":"Use the configured OpenAI-compatible Writer model to generate prose from the safe Writer context and save it as a non-canonical draft.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"title":{"type":"string"},"model":{"type":"string"},"declared_updates":{"type":"object"},"summary":{"type":"string","default":""}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_draft_save","title":"Save Chapter Draft","description":"Save externally generated or revised prose as a versioned, non-canonical chapter draft. Canon is unchanged until chapter_finalize passes the review gate.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"title":{"type":"string","minLength":1},"body":{"type":"string","minLength":1},"arc":{"type":"string","default":""},"pov":{"type":"string","default":""},"summary":{"type":"string","default":""},"declared_updates":{"type":"object"},"source":{"type":"string","default":"external"},"model":{"type":"string","default":""},"parent_version":{"type":"integer","minimum":1}},"required":["chapter","title","body"],"additionalProperties":False}},
 {"name":"chapter_draft_get","title":"Get Chapter Draft","description":"Get the latest or a specific version of a non-canonical chapter draft.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"version":{"type":"integer","minimum":1}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_review_all","title":"Run Chapter Reviewers","description":"Run four independent deterministic review gates on a draft: knowledge leak, continuity, narrative-plan adherence, and character consistency. Returns PASS/WARN/BLOCK evidence.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"version":{"type":"integer","minimum":1}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_review_get","title":"Get Chapter Reviews","description":"Get the review bundle for the latest or a specific draft version.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"version":{"type":"integer","minimum":1}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_revision_context_get","title":"Get Revision Context","description":"Build a revision package containing the draft, reviewer findings, safe Writer context, and revision discipline.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"version":{"type":"integer","minimum":1}},"required":["chapter"],"additionalProperties":False}},
 {"name":"writing_workflow_status","title":"Get Writing Workflow Status","description":"Inspect ChapterPlan, all draft versions, active draft, workflow state, and latest review verdict for one chapter.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_finalize","title":"Finalize and Commit Chapter","description":"Final commit gate. Requires a valid ChapterPlan and complete reviews for the exact draft version. Can require semantic reviewers in addition to deterministic gates.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"version":{"type":"integer","minimum":1},"allow_warnings":{"type":"boolean","default":True},"auto_extract":{"type":"boolean","default":False},"override_block":{"type":"boolean","default":False},"override_reason":{"type":"string","default":""},"require_semantic":{"type":"boolean","default":False}},"required":["chapter"],"additionalProperties":False}},

 # 语义审校者 / 自动修订运行时 v0.4
 {"name":"chapter_semantic_review","title":"Run Semantic Chapter Review","description":"Run model-based author-aware semantic reviewers for paraphrased secret leakage, character OOC, narrative/reveal intensity, and pacing. Hidden World Truth is used internally and redacted from returned findings.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"version":{"type":"integer","minimum":1},"model":{"type":"string"}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_review_full","title":"Run Full Chapter Review","description":"Run deterministic reviewers and, by default, the semantic reviewer family on the same exact draft version, then return the combined review gate.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"version":{"type":"integer","minimum":1},"semantic":{"type":"boolean","default":True},"model":{"type":"string"}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_auto_revise","title":"Auto Revise Chapter Draft","description":"Use the configured revision model to repair BLOCK and optional WARN findings without exposing hidden World Truth to the revision Writer. Saves a new draft version that must be reviewed again.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"version":{"type":"integer","minimum":1},"model":{"type":"string"},"include_warnings":{"type":"boolean","default":True}},"required":["chapter"],"additionalProperties":False}},
 {"name":"chapter_auto_revision_loop","title":"Run Auto Revision Loop","description":"Review the active draft, automatically revise blocked versions, re-review every new version, and optionally finalize once the exact current version passes. Revision approvals never carry across versions.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"version":{"type":"integer","minimum":1},"max_rounds":{"type":"integer","minimum":0,"maximum":8,"default":3},"require_semantic":{"type":"boolean","default":True},"reviewer_model":{"type":"string"},"revision_model":{"type":"string"},"finalize":{"type":"boolean","default":False},"allow_warnings":{"type":"boolean","default":True},"auto_extract":{"type":"boolean","default":False}},"required":["chapter"],"additionalProperties":False}},

 # Extraction Candidate Promotion v0.8 (A0)
 # chapter_commit 已从公开工具面移除:正典提交统一走 chapter_finalize 审校门。
 {"name":"candidate_list","title":"List Extraction Candidates","description":"List extraction candidates discovered from committed prose. Candidates are Mention-layer only: they never mutate canon until explicitly promoted.","inputSchema":{"type":"object","properties":{"chapter":{"type":"integer","minimum":0},"node_type":{"type":"string"},"status":{"type":"string","enum":["candidate","promoted","rejected"],"default":"candidate"},"limit":{"type":"integer","minimum":1,"maximum":500,"default":100}},"additionalProperties":False}},
 {"name":"candidate_promote","title":"Promote Extraction Candidate","description":"Explicitly promote one extraction candidate into a canonical Entity or World Fact, recording an evidence chain (chapter, extractor, confidence, source evidence). This is the only path from extraction to canon.","inputSchema":{"type":"object","properties":{"candidate_id":{"type":"integer","minimum":1},"target":{"type":"object","properties":{"kind":{"type":"string","enum":["entity","world_fact"]},"entity_key":{"type":"string"},"entity_type":{"type":"string"},"name":{"type":"string"},"description":{"type":"string"},"status":{"type":"string"},"fact_key":{"type":"string"},"truth":{},"secrecy":{"type":"string","default":"secret"},"reveal_after":{"type":"integer","minimum":0},"notes":{"type":"string"},"note":{"type":"string"}},"additionalProperties":False}},"required":["candidate_id"],"additionalProperties":False}},
 {"name":"candidate_reject","title":"Reject Extraction Candidate","description":"Reject an extraction candidate with an optional reason. Kept for audit; rejected candidates never enter canon.","inputSchema":{"type":"object","properties":{"candidate_id":{"type":"integer","minimum":1},"reason":{"type":"string","default":""}},"required":["candidate_id"],"additionalProperties":False}},

 # World Model V2: identity / first-class events / assertions
 {"name":"identity_profile_set","title":"Set Identity Profile","description":"Create or update a first-class identity profile: name, alias, pseudonym, disguise, role/title/position, or incarnation. Supports secrecy gating, World Fact binding, and a parent chain for identity continuity across lives.","inputSchema":{"type":"object","properties":{"profile":{"type":"object","properties":{"profile_key":{"type":"string","minLength":1},"entity_key":{"type":"string","minLength":1},"kind":{"type":"string","enum":["name","alias","role","title","position","incarnation","disguise","pseudonym","other"]},"value":{"type":"string","minLength":1},"scope_key":{"type":"string"},"secrecy":{"type":"string","enum":["public","secret","author_only"],"default":"public"},"reveal_after":{"type":"integer","minimum":0},"fact_key":{"type":"string"},"start_chapter":{"type":"integer","minimum":0,"default":0},"end_chapter":{"type":"integer","minimum":0},"parent_profile_key":{"type":"string"},"notes":{"type":"string"},"source":{"type":"string","default":"author_declared"},"confidence":{"type":"number","minimum":0,"maximum":1,"default":1}},"required":["profile_key","entity_key","kind","value"],"additionalProperties":False}},"required":["profile"],"additionalProperties":False}},
 {"name":"event_create","title":"Create Event","description":"Create or update a first-class story event with participants, location, cause chain, outcome and consequence. Participants become cross-layer retrieval anchors. Idempotent by event_key.","inputSchema":{"type":"object","properties":{"name":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0},"event_key":{"type":"string"},"event_type":{"type":"string","default":"event"},"thread_key":{"type":"string"},"location_key":{"type":"string"},"cause_event_id":{"type":"integer","minimum":1},"cause_event_key":{"type":"string"},"outcome":{"type":"string","default":""},"consequence":{"type":"string","default":""},"status":{"type":"string","default":"verified"},"participants":{"type":"array","items":{"type":"object","properties":{"entity_key":{"type":"string","minLength":1},"participant_role":{"type":"string","default":"participant"},"outcome_state":{"type":"object"}},"required":["entity_key"],"additionalProperties":False}},"metadata":{"type":"object"}},"required":["name","chapter"],"additionalProperties":False}},
 {"name":"event_get","title":"Get Event","description":"Get one first-class event with participants, its cause chain, and its direct effects.","inputSchema":{"type":"object","properties":{"event_key":{"type":"string"},"event_id":{"type":"integer","minimum":1}},"additionalProperties":False}},
 {"name":"event_timeline","title":"Event Timeline","description":"Query the world event timeline, optionally filtered to one participant entity and a chapter range. Backs the Timeline/Event Explorer.","inputSchema":{"type":"object","properties":{"entity_key":{"type":"string"},"from_chapter":{"type":"integer","minimum":0},"to_chapter":{"type":"integer","minimum":0},"limit":{"type":"integer","minimum":1,"maximum":500,"default":100}},"additionalProperties":False}},
 {"name":"assertion_create","title":"Create Assertion","description":"Record a candidate fact assertion with evidence (subject, predicate, object, chapter, source span, extractor, confidence). Extraction sources stay candidate; only the author confirms via assertion_resolve.","inputSchema":{"type":"object","properties":{"subject_key":{"type":"string","minLength":1},"predicate":{"type":"string","minLength":1},"object_value":{},"chapter":{"type":"integer","minimum":0,"default":0},"subject_type":{"type":"string","default":"entity"},"source_span":{"type":"string"},"extractor":{"type":"string","default":"author_declared"},"confidence":{"type":"number","minimum":0,"maximum":1,"default":1},"evidence":{"type":"string"},"event_id":{"type":"integer","minimum":1}},"required":["subject_key","predicate"],"additionalProperties":False}},
 {"name":"assertion_list","title":"List Assertions","description":"List fact assertions by subject, predicate, or truth status (candidate/confirmed/disproved/superseded).","inputSchema":{"type":"object","properties":{"subject_key":{"type":"string"},"subject_type":{"type":"string"},"predicate":{"type":"string"},"truth_status":{"type":"string","enum":["candidate","confirmed","disproved","superseded"]},"limit":{"type":"integer","minimum":1,"maximum":500,"default":100}},"additionalProperties":False}},
 {"name":"assertion_resolve","title":"Resolve Assertion","description":"Author-only assertion resolution: confirm, disprove, or supersede with a replacement assertion id. Terminal transitions are one-way.","inputSchema":{"type":"object","properties":{"assertion_id":{"type":"integer","minimum":1},"truth_status":{"type":"string","enum":["confirmed","disproved","superseded"]},"superseded_by":{"type":"integer","minimum":1}},"required":["assertion_id","truth_status"],"additionalProperties":False}},

 # Dual-time disclosures + professional subgraphs (Phase A batch 2)
 {"name":"fact_disclosure_set","title":"Schedule Fact Disclosure","description":"Dual-time knowledge scheduling: set when a holder (a character key, or 'reader' for global publication) legally learns a World Fact. Per-holder moments replace the single global reveal_after gate; earliest applicable moment wins.","inputSchema":{"type":"object","properties":{"fact_key":{"type":"string","minLength":1},"holder":{"type":"string","minLength":1},"known_from_chapter":{"type":"integer","minimum":0},"channel":{"type":"string","default":""},"source":{"type":"string","default":"author_declared"}},"required":["fact_key","holder","known_from_chapter"],"additionalProperties":False}},
 {"name":"fact_disclosures_get","title":"List Fact Disclosures","description":"List scheduled knowledge-time disclosures, optionally filtered by fact. Reader rows act as global publication moments.","inputSchema":{"type":"object","properties":{"fact_key":{"type":"string"}},"additionalProperties":False}},
 {"name":"power_context_get","title":"Get Power Context","description":"Author-layer Power subgraph view for one character: current power state, full realm/bloodline/physique/skill progression ladders with cause events, and lineage relations.","inputSchema":{"type":"object","properties":{"entity_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0}},"required":["entity_key","chapter"],"additionalProperties":False}},
 {"name":"artifact_history_get","title":"Get Artifact History","description":"Author-layer Artifact subgraph view: full custody/binding/seal/fusion/awakening relation history and state attribute ladders with cause events.","inputSchema":{"type":"object","properties":{"entity_key":{"type":"string","minLength":1}},"required":["entity_key"],"additionalProperties":False}},
 {"name":"geography_tree_get","title":"Get Geography Tree","description":"Visibility-filtered spatial containment subtree (LOCATED_IN/PART_OF/TERRITORY_OF...) from a root entity at a chapter. Backs the world-map and territory views.","inputSchema":{"type":"object","properties":{"root_entity_key":{"type":"string","minLength":1},"chapter":{"type":"integer","minimum":0},"holder":{"type":"string","default":"reader"},"relation_types":{"type":"array","items":{"type":"string"}},"max_depth":{"type":"integer","minimum":1,"maximum":8,"default":4},"limit":{"type":"integer","minimum":1,"maximum":500,"default":100}},"required":["root_entity_key","chapter"],"additionalProperties":False}},

]

TOOL_BY_NAME={t["name"]:t for t in TOOLS}

# 供无依赖兼容适配器使用的显式 schema。官方 SDK v2
# 也会从 Python 返回类型注解推导结构化输出。
_LIST_RESULTS={'narrative_thread_search','foreshadowing_list_open','milestone_list','thread_schedule_get','novel_run_decision_list','entity_search','narrative_entity_links_get','candidate_list','event_timeline','assertion_list','fact_disclosures_get'}
for _t in TOOLS:
    _t['outputSchema']={'type':'array','items':{'type':'object'}} if _t['name'] in _LIST_RESULTS else {'type':'object'}
